FROM golang as dev

ENV GO111MODULE=on \
  CGO_ENABLED=0 \
  GOOS=linux

# make
# RUN apt-get update && apt-get upgrade

# app
WORKDIR /usr/app

COPY . .

# for compile
RUN go get github.com/githubnemo/CompileDaemon

# go dependencies
RUN go get

EXPOSE 3000

ENTRYPOINT /go/bin/CompileDaemon -include="Makefile" --build="make" --command="/usr/app/bin/ecs api --config ecs.config.yml" -log-prefix=true
